"use client";
import Head from "next/head";
import Brand from "../../components/Brand";
import FormSignin from "../../components/FormSignin";
import Navbar from "../../components/Navbar";
import React, { useEffect } from "react";
import Cookies from "js-cookie";
import { redirect } from "next/navigation";
export default function Home() {
  // const token = Cookies.get("token", "value");
  // console.log("token signin");
  // console.log(token);

  useEffect(() => {
    const token = Cookies.get("token");
    // console.log("token signin");
    // console.log(token);
    if (token) {
      redirect("/");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>
      <section className="login header bg-navy">
        <div className="container">
          <div className="d-flex flex-column align-items-center hero gap-5">
            <div>
              <div className="hero-headline text-start">Sign In</div>
            </div>
            <FormSignin />
          </div>
        </div>
      </section>
      <Brand className="pt-0 bg-navy" />
    </>
  );
}

// export async function getServerSideProps(context) {
//   const { token } = context.req.cookies;

//   if (token) {
//     return {
//       redirect: {
//         destination: "/",
//         permanent: false,
//       },
//     };
//   }

//   return {
//     props: {},
//   };
// }
