/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
"use client";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Button from "../../../components/Button";
import CardEvent from "../../../components/CardEvent";
import Footer from "../../../components/Footer";
import Navbar from "../../../components/Navbar";
import Statistics from "../../../components/Statistics";
import Stories from "../../../components/Stories";
import { useRouter, useParams } from "next/navigation";
import { getData } from "../../../utils/fetchData";
import moment from "moment";
// export const dynamic = "force-dynamic";
import { formatDate } from "../../../utils/formatDate";
import Cookies from "js-cookie";

export default function DetailPage() {
  const [data, setData] = useState([]);
  const router = useRouter();
  const params = useParams();

  useEffect(() => {
    const fetchData = async () => {
      const req = await getData(`/api/v1/events/${params.id}`);
      setData(req.data.data);
    };

    fetchData();
  }, []);

  const handleSubmit = (ticketId, organizer) => {
    const token = Cookies.get("token");
    if (!token) {
      return router.push("/signin");
    } else {
      router.push(
        `/checkout/${params.id}?ticketId=${ticketId}&organizer=${organizer}`
      );
    }
  };
  return (
    <>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <div className="preview-image bg-navy text-center">
        <img
          src="/images/details-image.png"
          className="img-content"
          alt="semina"
        />
      </div>

      <div className="details-content container">
        <div className="d-flex flex-wrap justify-content-lg-center gap">
          <div className="d-flex flex-column description">
            <div className="headline">{data.title}</div>
            <br />
            <div className="event-details">
              <h6>Event Details</h6>
              <p className="details-paragraph">{data.about}</p>
            </div>
            <div className="keypoints">
              {/* YANG BERJALAN */}
              {/* {/* ceritanya erro terus tentang map tidak bisa menbaca/ reading 
              jadi aku buat sebuaha data itu dilooping kemudian di jadikan object terus dimaping
              lagi
              */}
              {/* {Object.values(data).map((data, i) => {
                // console.log("data looping");
                const point = data.keyPoint.map((keyPoint, key) => {
                  // console.log(keyPoint);
                  return keyPoint;
                });
                return (
                  <div className="d-flex align-items-start gap-3" key={i}>
                    <img src="/icons/ic-check.svg" alt="semina" />
                    <span>{point}</span>
                  </div>
                );
              })} */}
              {/* ===================================================== */}
              {/* YANG BENER */}
              {data?.keyPoint?.map((key, i) => {
                return (
                  <div className="d-flex align-items-start gap-3" key={i}>
                    <img src="/icons/ic-check.svg" alt="semina" />
                    <span>{key}</span>
                  </div>
                );
              })}
            </div>
            <div className="map-location">
              <h6>Event Location</h6>
              <div className="map-placeholder">
                <div className="maps">
                  <img src="/images/maps.png" alt="" />
                  <div
                    className="absolute d-flex justify-content-center align-items-center"
                    id="hoverMe"
                  >
                    <a href="#" className="btn-navy" id="btn-maps">
                      View in Google Maps
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="d-flex flex-column card-event">
            <h6>Your Speaker</h6>
            <div className="d-flex align-items-center gap-3 mt-3">
              <img
                src={`${process.env.NEXT_PUBLIC_API}/${data?.talent?.image?.name}`}
                alt="semina"
                width="60"
              />
              <div>
                <div className="speaker-name">{data?.talent?.name}</div>
                <span className="occupation">{data?.talent?.role}</span>
              </div>
            </div>
            <hr />

            <h6>Get Ticket</h6>
            {data?.tickets?.map((ticket) => (
              <>
                {ticket.statusTicketCategories ? (
                  <>
                    <div className="price my-3">
                      {ticket.price === 0 ? "free" : `$${ticket.price}`}
                      <span>/person</span>
                    </div>
                    <div className="d-flex gap-3 align-items-center card-details">
                      <img src="/icons/ic-marker.svg" alt="semina" />{" "}
                      {data?.venueName}
                    </div>
                    <div className="d-flex gap-3 align-items-center card-details">
                      <img src="/icons/ic-time.svg" alt="semina" />{" "}
                      {moment(data?.date).format("HH.MM A")}
                    </div>
                    <div className="d-flex gap-3 align-items-center card-details">
                      <img src="/icons/ic-calendar.svg" alt="semina" />{" "}
                      {formatDate(data?.date)}
                    </div>

                    {data?.stock !== 0 && (
                      <Button
                        variant={"btn-green"}
                        action={() => handleSubmit(ticket._id, data?.organizer)}
                      >
                        Join Now
                      </Button>
                    )}
                  </>
                ) : (
                  ""
                )}
              </>
            ))}
          </div>
        </div>
      </div>

      {/* <CardEvent data={data} title="Similiar Events" subTitle="Next One" /> */}
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}
